version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"      # AMQP protocol port
      - "15672:15672"    # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    networks:
      - message_broker_network
    restart: unless-stopped

volumes:
  rabbitmq_data:
  rabbitmq_logs:

networks:
  message_broker_network:
    driver: bridge
